base_url = "https://prankrs.dev/"

title = "Prank | Build, bundle & ship your Rust WASM application to the web"

compile_sass = true
build_search_index = true
generate_feeds = true

theme = "juice"

[markdown]
highlight_code = true
highlight_theme = "inspired-github"

[extra]
favicon = "rustacean-flat-happy.svg"
juice_logo_name = "Prank"
juice_logo_path = "rustacean-flat-happy.svg"
juice_extra_menu = [
    { title = "Guide", link = "https://prankrs.dev/guide"},
    { title = "GitHub", link = "https://github.com/prank-rs/prank"}
]

# hide these ad they have moved
juice_exclude_menu = [ "Advanced", "Assets", "Commands", "Configuration" ]